DROP TABLE IF EXISTS Buku;
CREATE TABLE Buku
(
id INT(5) NOT NULL PRIMARY KEY auto_increment,
JudulBuku VARCHAR(50) NOT NULL,
Jumlah VARCHAR(50) NOT NULL,
Pengarang VARCHAR(50) NOT NULL,
Penerbit VARCHAR(50) NOT NULL,
KotaTerbit VARCHAR(50) NOT NULL,
TahunTerbit VARCHAR(50) NOT NULL,
Harga VARCHAR(50) NOT NULL,
Deskripsi TEXT,
Sampul VARCHAR(50)
)ENGINE=INNODB;
